// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _About_Annotation_Removed_forFluentValidation_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_About_Annotation_Removed_forFluentValidation_));
        
        string IMigrationMetadata.Id
        {
            get { return "202208251620445__About_Annotation_Removed_forFluentValidation_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
