// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _Blog_BlogRating_Added_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_Blog_BlogRating_Added_));
        
        string IMigrationMetadata.Id
        {
            get { return "202208221606541__Blog_BlogRating_Added_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
