// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _Author_Comment_Connected_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_Author_Comment_Connected_));
        
        string IMigrationMetadata.Id
        {
            get { return "202208192039442__Author_Comment_Connected_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
