// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _Category_CategoryDescription_Added_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_Category_CategoryDescription_Added_));
        
        string IMigrationMetadata.Id
        {
            get { return "202208201338122__Category_CategoryDescription_Added_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
